const STRINGS = {
  en: {
    appTitle: "AI Window Deck",
    appSubtitle: "Your windows, split inside one app",
    windowsHeader: "Windows",
    windowsHint: "Click a pane's title bar to bring it forward. Double-click a card to edit.",
    addWindow: "Add window",
    editWindow: "Edit window",
    importBackup: "Import from extension",
    importHint: "Backup .json or window list .txt",
    importedMsg: "Imported {count} windows",
    importFailedMsg: "Could not read that file",
    showPane: "Show {name} in the deck",
    hidePane: "Hide {name} from the deck",
    deleteItem: "Delete {name}",
    untitledWindow: "Untitled",
    urlsCount: "URLs",
    urlSingular: "URL",
    nameLabel: "Name",
    urlsLabel: "URLs (one per tab)",
    addUrl: "Add URL",
    removeUrl: "Remove URL",
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    modeGrid: "Grid",
    modeSpotlight: "Spotlight",
    modeFill: "Fill",
    modeLabel: "Layout",
    sidebarToggle: "Show / hide sidebar",
    back: "Back",
    forward: "Forward",
    reload: "Reload",
    enlarge: "Spotlight this pane",
    shrink: "Back to grid",
    fill: "Fill the deck",
    hide: "Hide from deck",
    emptyDeck: "No windows are showing",
    emptyDeckHint: "Turn a window on in the sidebar, or add one with +.",
    loadFailed: "Couldn't load this page",
    retry: "Retry",
    shortcuts: "Shortcuts",
    kbSpotlight: "Spotlight / back",
    kbHome: "Back to grid",
    kbFill: "Fill the deck",
    kbFocus: "Focus pane 1–8",
    kbCycle: "Next / previous pane",
    kbSidebar: "Sidebar",
    languageLabel: "Language",
  },
  ja: {
    appTitle: "AI Window Deck",
    appSubtitle: "登録したウィンドウを、1 つのアプリの中で分割表示",
    windowsHeader: "ウィンドウ",
    windowsHint: "ペインのタイトルバーをクリックすると拡大します。カードをダブルクリックで編集。",
    addWindow: "ウィンドウを追加",
    editWindow: "ウィンドウを編集",
    importBackup: "拡張機能から読み込む",
    importHint: "バックアップ .json またはウィンドウ一覧 .txt",
    importedMsg: "{count} 件のウィンドウを読み込みました",
    importFailedMsg: "このファイルを読み込めませんでした",
    showPane: "{name} をデッキに表示",
    hidePane: "{name} をデッキから隠す",
    deleteItem: "{name} を削除",
    untitledWindow: "無題",
    urlsCount: "URL",
    urlSingular: "URL",
    nameLabel: "名前",
    urlsLabel: "URL（1 行 1 タブ）",
    addUrl: "URL を追加",
    removeUrl: "URL を削除",
    cancel: "キャンセル",
    save: "保存",
    close: "閉じる",
    modeGrid: "グリッド",
    modeSpotlight: "Spotlight",
    modeFill: "全面",
    modeLabel: "レイアウト",
    sidebarToggle: "サイドバーの表示 / 非表示",
    back: "戻る",
    forward: "進む",
    reload: "再読み込み",
    enlarge: "このペインを拡大",
    shrink: "グリッドに戻す",
    fill: "デッキ全体に広げる",
    hide: "デッキから隠す",
    emptyDeck: "表示中のウィンドウがありません",
    emptyDeckHint: "サイドバーでウィンドウをオンにするか、+ で追加してください。",
    loadFailed: "このページを読み込めませんでした",
    retry: "再試行",
    shortcuts: "ショートカット",
    kbSpotlight: "拡大 / 戻す",
    kbHome: "グリッドに戻す",
    kbFill: "デッキ全体に広げる",
    kbFocus: "ペイン 1〜8 にフォーカス",
    kbCycle: "次 / 前のペイン",
    kbSidebar: "サイドバー",
    languageLabel: "言語",
  },
};

export const LANGUAGES = [
  { code: "ja", label: "日本語" },
  { code: "en", label: "English" },
];

export function resolveLanguage(tag) {
  return String(tag || "").toLowerCase().startsWith("ja") ? "ja" : "en";
}

export function translator(lang) {
  return (key, values) => {
    const text = STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;
    if (!values) return text;
    return text.replace(/\{(\w+)\}/g, (match, name) => (name in values ? String(values[name]) : match));
  };
}
