#!/usr/bin/env python3
"""Generate the extension's translation files from tools/strings.json.

Two outputs, because Chrome splits the job in two:

  strings.js   the popup copy, switchable at runtime from the panel
  _locales/    the name and description Chrome itself renders, which always
               follow the browser UI language and cannot be overridden

    python3 tools/build-i18n.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "tools" / "strings.json"
DEFAULT_LOCALE = "en"


def chrome_dir(locale):
    """Chrome uses underscores in _locales folder names: zh-CN -> zh_CN."""
    return locale.replace("-", "_")


def main():
    strings = json.loads(SOURCE.read_text(encoding="utf-8"))
    expected = set(strings[DEFAULT_LOCALE])

    # A key a locale has not been translated into yet falls back to the default
    # locale, which is what the runtime does anyway. A key nobody asked for is
    # drift and stops the build.
    for locale, entries in strings.items():
        extra = set(entries) - expected
        if extra:
            raise SystemExit(f"{locale}: unknown keys {sorted(extra)}")
        missing = sorted(expected - set(entries))
        if missing:
            print(f"  ! {locale}: {len(missing)} untranslated, using {DEFAULT_LOCALE}: {missing}")
            for key in missing:
                entries[key] = strings[DEFAULT_LOCALE][key]

    banner = "// Generated by tools/build-i18n.py from tools/strings.json. Do not edit.\n"
    body = json.dumps(strings, ensure_ascii=False, indent=2, sort_keys=False)
    (ROOT / "strings.js").write_text(f"{banner}const STRINGS = {body};\n", encoding="utf-8")
    print(f"wrote strings.js ({len(strings)} locales, {len(expected)} keys each)")

    locales_dir = ROOT / "_locales"
    for locale, entries in strings.items():
        target = locales_dir / chrome_dir(locale)
        target.mkdir(parents=True, exist_ok=True)
        messages = {
            "extName": {"message": "AI Window Deck"},
            "extDescription": {"message": entries["ext_description"]},
        }
        (target / "messages.json").write_text(
            json.dumps(messages, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        print(f"wrote _locales/{chrome_dir(locale)}/messages.json")


if __name__ == "__main__":
    main()
