#!/usr/bin/env python3
"""Generate the extension's translation files from tools/strings.json.

Three outputs, because Chrome splits the job in two and the panel is React:

  strings.js            the legacy deck copy, switchable at runtime
  src/lib/ui-strings.js the React panel copy, from tools/ui-strings.json
  _locales/             the name, description and keyboard-command labels
                        Chrome itself renders, which always follow the browser
                        UI language and cannot be overridden

    python3 tools/build-i18n.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "tools" / "strings.json"
UI_SOURCE = ROOT / "tools" / "ui-strings.json"
DEFAULT_LOCALE = "en"

# manifest.json "commands" descriptions -> __MSG_<name>__ keys in _locales.
COMMAND_MESSAGES = {
    "cmdSpotlight": "cmd_spotlight",
    "cmdHome": "cmd_home",
    "cmdTile": "cmd_tile",
    "cmdFullscreen": "cmd_fullscreen",
    "cmdUndo": "cmd_undo",
    "cmdNext": "cmd_next",
    "cmdPrev": "cmd_prev",
}
FOCUS_TILE_COUNT = 8


def chrome_dir(locale):
    """Chrome uses underscores in _locales folder names: zh-CN -> zh_CN."""
    return locale.replace("-", "_")


def main():
    strings = json.loads(SOURCE.read_text(encoding="utf-8"))
    expected = set(strings[DEFAULT_LOCALE])

    # A key a locale has not been translated into yet falls back to the default
    # locale, which is what the runtime does anyway. A key nobody asked for is
    # drift and stops the build.
    for locale, entries in strings.items():
        extra = set(entries) - expected
        if extra:
            raise SystemExit(f"{locale}: unknown keys {sorted(extra)}")
        missing = sorted(expected - set(entries))
        if missing:
            print(f"  ! {locale}: {len(missing)} untranslated, using {DEFAULT_LOCALE}: {missing}")
            for key in missing:
                entries[key] = strings[DEFAULT_LOCALE][key]

    banner = "// Generated by tools/build-i18n.py from tools/strings.json. Do not edit.\n"
    body = json.dumps(strings, ensure_ascii=False, indent=2, sort_keys=False)
    (ROOT / "strings.js").write_text(f"{banner}const STRINGS = {body};\n", encoding="utf-8")
    print(f"wrote strings.js ({len(strings)} locales, {len(expected)} keys each)")

    locales_dir = ROOT / "_locales"
    for locale, entries in strings.items():
        target = locales_dir / chrome_dir(locale)
        target.mkdir(parents=True, exist_ok=True)
        messages = {
            "extName": {"message": "AI Window Deck"},
            "extDescription": {"message": entries["ext_description"]},
        }
        for message, key in COMMAND_MESSAGES.items():
            messages[message] = {"message": entries[key]}
        for n in range(1, FOCUS_TILE_COUNT + 1):
            messages[f"cmdFocusTile{n}"] = {"message": entries["cmd_focus_tile"].replace("{n}", str(n))}
        (target / "messages.json").write_text(
            json.dumps(messages, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        print(f"wrote _locales/{chrome_dir(locale)}/messages.json")

    build_ui_strings(list(strings))


def build_ui_strings(locales):
    """The React panel ships every locale complete: a missing key fails the
    build instead of silently showing English inside a translated screen."""
    ui = json.loads(UI_SOURCE.read_text(encoding="utf-8"))
    expected = set(ui[DEFAULT_LOCALE])
    problems = []
    for locale in locales:
        entries = ui.get(locale)
        if entries is None:
            problems.append(f"{locale}: missing from ui-strings.json")
            continue
        missing = sorted(expected - set(entries))
        extra = sorted(set(entries) - expected)
        if missing or extra:
            problems.append(f"{locale}: missing {missing} extra {extra}")
    if problems:
        raise SystemExit("ui-strings.json:\n  " + "\n  ".join(problems))
    ordered = {locale: ui[locale] for locale in locales}
    body = json.dumps(ordered, ensure_ascii=False, indent=2)
    banner = "// Generated by tools/build-i18n.py from tools/ui-strings.json. Do not edit.\n"
    (ROOT / "src" / "lib" / "ui-strings.js").write_text(
        f"{banner}export const UI_STRINGS = {body};\n", encoding="utf-8")
    print(f"wrote src/lib/ui-strings.js ({len(locales)} locales, {len(expected)} keys each)")


if __name__ == "__main__":
    main()
